#############################################################################
# Makefile for building: cameraandchpin
# Generated by qmake (2.01a) (Qt 4.8.1) on: ?? 7? 6 09:49:28 2016
# Project:  cameraandchpin.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile cameraandchpin.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = camera.cpp \
		camera_thread.cpp \
		canread.cpp \
		dialog.cpp \
		main.cpp \
		signalcan.cpp \
		v4l2.cpp \
		widget.cpp moc_camera.cpp \
		moc_camera_thread.cpp \
		moc_dialog.cpp \
		moc_signalcan.cpp \
		moc_widget.cpp
OBJECTS       = camera.o \
		camera_thread.o \
		canread.o \
		dialog.o \
		main.o \
		signalcan.o \
		v4l2.o \
		widget.o \
		moc_camera.o \
		moc_camera_thread.o \
		moc_dialog.o \
		moc_signalcan.o \
		moc_widget.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		cameraandchpin.pro
QMAKE_TARGET  = cameraandchpin
DESTDIR       = 
TARGET        = cameraandchpin

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_camera.h ui_dialog.h ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cameraandchpin.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile cameraandchpin.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile cameraandchpin.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cameraandchpin1.0.0 || $(MKDIR) .tmp/cameraandchpin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cameraandchpin1.0.0/ && $(COPY_FILE) --parents camera.h camera_thread.h canread.h dialog.h signalcan.h v4l2.h widget.h .tmp/cameraandchpin1.0.0/ && $(COPY_FILE) --parents camera.cpp camera_thread.cpp canread.cpp dialog.cpp main.cpp signalcan.cpp v4l2.cpp widget.cpp .tmp/cameraandchpin1.0.0/ && $(COPY_FILE) --parents camera.ui dialog.ui widget.ui .tmp/cameraandchpin1.0.0/ && (cd `dirname .tmp/cameraandchpin1.0.0` && $(TAR) cameraandchpin1.0.0.tar cameraandchpin1.0.0 && $(COMPRESS) cameraandchpin1.0.0.tar) && $(MOVE) `dirname .tmp/cameraandchpin1.0.0`/cameraandchpin1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cameraandchpin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_camera.cpp moc_camera_thread.cpp moc_dialog.cpp moc_signalcan.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_camera.cpp moc_camera_thread.cpp moc_dialog.cpp moc_signalcan.cpp moc_widget.cpp
moc_camera.cpp: camera_thread.h \
		v4l2.h \
		camera.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) camera.h -o moc_camera.cpp

moc_camera_thread.cpp: v4l2.h \
		camera_thread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) camera_thread.h -o moc_camera_thread.cpp

moc_dialog.cpp: dialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) dialog.h -o moc_dialog.cpp

moc_signalcan.cpp: canread.h \
		signalcan.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) signalcan.h -o moc_signalcan.cpp

moc_widget.cpp: dialog.h \
		signalcan.h \
		canread.h \
		camera.h \
		camera_thread.h \
		v4l2.h \
		widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_camera.h ui_dialog.h ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_camera.h ui_dialog.h ui_widget.h
ui_camera.h: camera.ui
	/usr/bin/uic-qt4 camera.ui -o ui_camera.h

ui_dialog.h: dialog.ui
	/usr/bin/uic-qt4 dialog.ui -o ui_dialog.h

ui_widget.h: widget.ui
	/usr/bin/uic-qt4 widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

camera.o: camera.cpp camera.h \
		camera_thread.h \
		v4l2.h \
		ui_camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

camera_thread.o: camera_thread.cpp camera_thread.h \
		v4l2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera_thread.o camera_thread.cpp

canread.o: canread.cpp canread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canread.o canread.cpp

dialog.o: dialog.cpp dialog.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

main.o: main.cpp widget.h \
		dialog.h \
		signalcan.h \
		canread.h \
		camera.h \
		camera_thread.h \
		v4l2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

signalcan.o: signalcan.cpp signalcan.h \
		canread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signalcan.o signalcan.cpp

v4l2.o: v4l2.cpp v4l2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o v4l2.o v4l2.cpp

widget.o: widget.cpp widget.h \
		dialog.h \
		signalcan.h \
		canread.h \
		camera.h \
		camera_thread.h \
		v4l2.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

moc_camera.o: moc_camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera.o moc_camera.cpp

moc_camera_thread.o: moc_camera_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera_thread.o moc_camera_thread.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_signalcan.o: moc_signalcan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_signalcan.o moc_signalcan.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

